<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Author ID' => '',
    'Blog ID' => '',
    'Code' => '',
    'Content' => '',
    'Created At' => '',
    'ID' => '',
    'Name En' => '',
    'Name Ru' => '',
    'Главная' => 'Home',
    'Статьи' => 'Blogs',
    'Магазин' => 'Shop',
    'Админка' => 'AdminZone',
    'Американский доллар' => 'Dollar',
    'Вход' => 'Enter',
    'Выход' => 'Exit',
    'Корзина' => 'Cart',
    'Мой заказ' => 'My order',
    'Обратная связь' => 'Contact us',
    'Отследить' => 'Checkout',
    'Поиск' => 'Search',
    'Регистрация' => 'Registration',
    'Росийский рубль' => 'Ruble',
    'Сменить язык' => 'Change language',
    'Список желаний' => 'Wish list',
    'Список сравнения' => 'To compare',
    'Список статей' => 'List blog',
    'Статья' => 'Blog',
    'Товары' => 'Goods',
    'Товары в деталях' => 'Details',
    'Украинская гривня' => 'Uan',
    'сменить валюту' => 'Change currency',
];
